<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SpecRunner.Cli\SpecRunner.Cli.csproj" />
    <ProjectReference Include="..\SpecRunner.Core\SpecRunner.Core.csproj" />
    <ProjectReference Include="..\SpecRunner.Git\SpecRunner.Git.csproj" />
    <ProjectReference Include="..\SpecRunner.GitHub\SpecRunner.GitHub.csproj" />
    <ProjectReference Include="..\SpecRunner.State\SpecRunner.State.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="CommandTemplates\**\*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>0274bd70-1035-4be0-9312-0238c9d5ca99</UserSecretsId>
  </PropertyGroup>

</Project>
